export interface IUserInputs {
    Scenario: string;
    stateId: number;
    SalesRegionId: string;
    CountyId: string[];
    PlanTypeId: string;
    SnpTypeId: string;
    CrossWalkId: string;
    PremiumMin: number;
    PremiumMax: number;
    bidId : string;
    IsPartDPremium: boolean;
    IsPartBGiveBack: boolean;
    IsPlanCoverage: boolean;
    EnrollmentMonth: string;
    EnrollmentFromMonth: string;
    EnrollmentToMonth: string;
    EnrollmentMin: number;
    EnrollmentMax: number;
    EnrollmentChangeMin: number;
    EnrollmentChangeMax: number;
    // IsHealthDeductible: boolean;
    // isDrugDeductible: boolean;
    HDMin: number;
    HDMax: number;
    DDMin: number;
    DDMax: number;
    MoopMin: number;
    MoopMax: number;
    isAmbulance: boolean;
    isComprehensiveDental: boolean;
    isChiropractor: boolean;
    isMeal: boolean;
    isFitness : boolean;
    isOTC : boolean;
    isVision : boolean;
    isHearing : boolean;
    isEmergency : boolean;
    isTeleHealth : boolean;
    ishomeSupport : boolean;
    isHomeSaftey : boolean;
    isPers : boolean;
    UserId : string;
    IsEnrollmentSelected : number;
    isSortBy : string;
    PlanBenefitGroups: string;
    isCostShareOnly: boolean;
}